name: Clean Jupyter Notebooks

on:
  push:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  clean:
    uses: anubhav-auth/anubhav-auth/.github/workflows/strip-nb.yml@main
